apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository  
    name: flux-system
  path: ./logging/loki
  prune: true
  validation: client
