apiVersion: v1
kind: Secret
metadata:
  name: discord-url
  namespace: mfa
data:
  address: >-
    aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvOTYwNTI0Nzg1NTM0Nzg3NjE0LzBHMnQ4b05EM1JEZDNvMk8tdzRQMFJqX2NGNGppcmZaTjhXVk1vb1RmVTNaeTkyX0x2THl4bnlWbTJscUdYcDd4V2lE
type: Opaque
